version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
    groups:
      dev-dependencies:
        update-types:
          - "minor"
          - "patch"
        dependency-type: "development"
      migrations-dev:
        update-types:
          - "major"
        dependency-type: "development"
      prod-dependencies:
        update-types:
          - "minor"
          - "patch"
        dependency-type: "production"
      migrations-prod:
        update-types:
          - "major"
        dependency-type: "production"
    labels:
      - "dependencies"
      - "dependabot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
