name: Maintain Git Garden

on:
  push:
    branches: [ main, master ]

jobs:
  maintain-garden:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: svanschooten/gitgarden/.github/workflows/gitgarden.yml@main
