name: Maintain Git Garden

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  garden:
    permissions:
      contents: write
    uses: svanschooten/gitgarden/.github/workflows/gitgarden.yml@main
